// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#include "../GUI.h"

void GUI_initScreen__OdometerScreen() {
    GUI_Screen__OdometerScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(GUI_Screen__OdometerScreen, LV_OBJ_FLAG_SCROLLABLE);
    GUI_Label__OdometerScreen__MainTitle = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__MainTitle, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__MainTitle, 32, 24);
    lv_obj_set_size(GUI_Label__OdometerScreen__MainTitle, 320, LV_SIZE_CONTENT);

    GUI_Container__OdometerScreen__Divider = lv_obj_create(GUI_Screen__OdometerScreen);
    lv_obj_remove_style_all(GUI_Container__OdometerScreen__Divider);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__Divider, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__Divider, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__OdometerScreen__Divider, LV_ALIGN_CENTER);
    lv_obj_set_y(GUI_Container__OdometerScreen__Divider, -144);
    lv_obj_set_size(GUI_Container__OdometerScreen__Divider, 800, 1);

    GUI_Container__OdometerScreen__VerticalDivider = lv_obj_create(GUI_Screen__OdometerScreen);
    lv_obj_remove_style_all(GUI_Container__OdometerScreen__VerticalDivider);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__VerticalDivider, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__VerticalDivider, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__OdometerScreen__VerticalDivider, LV_ALIGN_CENTER);
    lv_obj_set_pos(GUI_Container__OdometerScreen__VerticalDivider, 96, 48);
    lv_obj_set_size(GUI_Container__OdometerScreen__VerticalDivider, 1, 384);

    GUI_Label__OdometerScreen__LastRunLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunLabel, 520, 140);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LastRunDateLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunDateLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__LastRunDateLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunDateLabel, -24, 140);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunDateLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__DistanceTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__DistanceTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__DistanceTitleLabel, 32, 140);
    lv_obj_set_size(GUI_Label__OdometerScreen__DistanceTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__DistanceValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__DistanceValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__DistanceValueLabel, 32, 160);
    lv_obj_set_size(GUI_Label__OdometerScreen__DistanceValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__DistanceUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__DistanceUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__DistanceUnitLabel, 182, 165);
    lv_obj_set_size(GUI_Label__OdometerScreen__DistanceUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__RunsTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__RunsTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__RunsTitleLabel, 32, 220);
    lv_obj_set_size(GUI_Label__OdometerScreen__RunsTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__RunsValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__RunsValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__RunsValueLabel, 32, 240);
    lv_obj_set_size(GUI_Label__OdometerScreen__RunsValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__TimeTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__TimeTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__TimeTitleLabel, 32, 300);
    lv_obj_set_size(GUI_Label__OdometerScreen__TimeTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__TimeValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__TimeValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__TimeValueLabel, 32, 320);
    lv_obj_set_size(GUI_Label__OdometerScreen__TimeValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__TimeUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__TimeUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__TimeUnitLabel, 182, 325);
    lv_obj_set_size(GUI_Label__OdometerScreen__TimeUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ElevationTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ElevationTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ElevationTitleLabel, 32, 380);
    lv_obj_set_size(GUI_Label__OdometerScreen__ElevationTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ElevationValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ElevationValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ElevationValueLabel, 32, 400);
    lv_obj_set_size(GUI_Label__OdometerScreen__ElevationValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ElevationUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ElevationUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ElevationUnitLabel, 182, 405);
    lv_obj_set_size(GUI_Label__OdometerScreen__ElevationUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__7DaysTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__7DaysTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__7DaysTitleLabel, 280, 140);
    lv_obj_set_size(GUI_Label__OdometerScreen__7DaysTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__7DaysValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__7DaysValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__7DaysValueLabel, 280, 160);
    lv_obj_set_size(GUI_Label__OdometerScreen__7DaysValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__7DaysUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__7DaysUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__7DaysUnitLabel, 420, 165);
    lv_obj_set_size(GUI_Label__OdometerScreen__7DaysUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__30DaysTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__30DaysTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__30DaysTitleLabel, 280, 220);
    lv_obj_set_size(GUI_Label__OdometerScreen__30DaysTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__30DaysValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__30DaysValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__30DaysValueLabel, 280, 240);
    lv_obj_set_size(GUI_Label__OdometerScreen__30DaysValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__30DaysUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__30DaysUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__30DaysUnitLabel, 420, 245);
    lv_obj_set_size(GUI_Label__OdometerScreen__30DaysUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ThisYearTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ThisYearTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ThisYearTitleLabel, 280, 300);
    lv_obj_set_size(GUI_Label__OdometerScreen__ThisYearTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ThisYearValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ThisYearValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ThisYearValueLabel, 280, 320);
    lv_obj_set_size(GUI_Label__OdometerScreen__ThisYearValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__ThisYearUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__ThisYearUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__ThisYearUnitLabel, 420, 325);
    lv_obj_set_size(GUI_Label__OdometerScreen__ThisYearUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LongestRunTitleLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LongestRunTitleLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LongestRunTitleLabel, 280, 380);
    lv_obj_set_size(GUI_Label__OdometerScreen__LongestRunTitleLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LongestRunValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LongestRunValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LongestRunValueLabel, 280, 400);
    lv_obj_set_size(GUI_Label__OdometerScreen__LongestRunValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LongestRunUnitLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LongestRunUnitLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LongestRunUnitLabel, 420, 405);
    lv_obj_set_size(GUI_Label__OdometerScreen__LongestRunUnitLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Container__OdometerScreen__RoutePreviewContainer = lv_obj_create(GUI_Screen__OdometerScreen);
    lv_obj_remove_style_all(GUI_Container__OdometerScreen__RoutePreviewContainer);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__RoutePreviewContainer, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(GUI_Container__OdometerScreen__RoutePreviewContainer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_align(GUI_Container__OdometerScreen__RoutePreviewContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Container__OdometerScreen__RoutePreviewContainer, -62, 180);
    lv_obj_set_size(GUI_Container__OdometerScreen__RoutePreviewContainer, 180, 180);

    GUI_Image__OdometerScreen__DistanceIcon = lv_image_create(GUI_Screen__OdometerScreen);
    lv_obj_add_flag(GUI_Image__OdometerScreen__DistanceIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__OdometerScreen__DistanceIcon, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_pos(GUI_Image__OdometerScreen__DistanceIcon, 520, 380);
    lv_obj_set_size(GUI_Image__OdometerScreen__DistanceIcon, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LastRunDistanceLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunDistanceLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunDistanceLabel, 550, 379);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunDistanceLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__OdometerScreen__TimeIcon = lv_image_create(GUI_Screen__OdometerScreen);
    lv_obj_add_flag(GUI_Image__OdometerScreen__TimeIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__OdometerScreen__TimeIcon, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_pos(GUI_Image__OdometerScreen__TimeIcon, 690, 380);
    lv_obj_set_size(GUI_Image__OdometerScreen__TimeIcon, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LastRunTimeLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunTimeLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__LastRunTimeLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunTimeLabel, -24, 379);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunTimeLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__OdometerScreen__PaceIcon = lv_image_create(GUI_Screen__OdometerScreen);
    lv_obj_add_flag(GUI_Image__OdometerScreen__PaceIcon, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__OdometerScreen__PaceIcon, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_pos(GUI_Image__OdometerScreen__PaceIcon, 520, 415);
    lv_obj_set_size(GUI_Image__OdometerScreen__PaceIcon, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LastRunPaceLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunPaceLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunPaceLabel, 550, 414);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunPaceLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__LastRunElevationLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__LastRunElevationLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__LastRunElevationLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__LastRunElevationLabel, -24, 414);
    lv_obj_set_size(GUI_Label__OdometerScreen__LastRunElevationLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Image__OdometerScreen__TimeIcon_1 = lv_image_create(GUI_Screen__OdometerScreen);
    lv_obj_add_flag(GUI_Image__OdometerScreen__TimeIcon_1, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_remove_flag(GUI_Image__OdometerScreen__TimeIcon_1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_pos(GUI_Image__OdometerScreen__TimeIcon_1, 690, 415);
    lv_obj_set_size(GUI_Image__OdometerScreen__TimeIcon_1, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__DaysUntilValueLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__DaysUntilValueLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__DaysUntilValueLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__DaysUntilValueLabel, -145, 24);
    lv_obj_set_size(GUI_Label__OdometerScreen__DaysUntilValueLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__DaysUntilTextLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__DaysUntilTextLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__DaysUntilTextLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__DaysUntilTextLabel, -32, 32);
    lv_obj_set_size(GUI_Label__OdometerScreen__DaysUntilTextLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__NextRaceLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__NextRaceLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__NextRaceLabel, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__NextRaceLabel, -32, 56);
    lv_obj_set_size(GUI_Label__OdometerScreen__NextRaceLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__UpdatedTextLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__UpdatedTextLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__UpdatedTextLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__UpdatedTextLabel, 12, -6);
    lv_obj_set_size(GUI_Label__OdometerScreen__UpdatedTextLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_Label__OdometerScreen__UpdatedTimeLabel = lv_label_create(GUI_Screen__OdometerScreen);
    lv_label_set_long_mode(GUI_Label__OdometerScreen__UpdatedTimeLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_align(GUI_Label__OdometerScreen__UpdatedTimeLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_pos(GUI_Label__OdometerScreen__UpdatedTimeLabel, 70, -6);
    lv_obj_set_size(GUI_Label__OdometerScreen__UpdatedTimeLabel, LV_SIZE_CONTENT, LV_SIZE_CONTENT);

    GUI_initScreenStyles__OdometerScreen();
    GUI_initScreenTexts__OdometerScreen();
}

void GUI_initScreenTexts__OdometerScreen() {
    lv_label_set_text_static(GUI_Label__OdometerScreen__MainTitle, "Run Log");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunLabel, "LAST RUN");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunDateLabel, "AUG 08, 2026");
    lv_label_set_text_static(GUI_Label__OdometerScreen__DistanceTitleLabel, "DISTANCE");
    lv_label_set_text_static(GUI_Label__OdometerScreen__DistanceValueLabel, "1000.0");
    lv_label_set_text_static(GUI_Label__OdometerScreen__DistanceUnitLabel, "km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__RunsTitleLabel, "RUNS");
    lv_label_set_text_static(GUI_Label__OdometerScreen__RunsValueLabel, "212");
    lv_label_set_text_static(GUI_Label__OdometerScreen__TimeTitleLabel, "TIME");
    lv_label_set_text_static(GUI_Label__OdometerScreen__TimeValueLabel, "200.5");
    lv_label_set_text_static(GUI_Label__OdometerScreen__TimeUnitLabel, "hr");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ElevationTitleLabel, "ELEVATION");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ElevationValueLabel, "10000.4");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ElevationUnitLabel, "m");
    lv_label_set_text_static(GUI_Label__OdometerScreen__7DaysTitleLabel, "7 DAYS");
    lv_label_set_text_static(GUI_Label__OdometerScreen__7DaysValueLabel, "27.2");
    lv_label_set_text_static(GUI_Label__OdometerScreen__7DaysUnitLabel, "km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__30DaysTitleLabel, "30 DAYS");
    lv_label_set_text_static(GUI_Label__OdometerScreen__30DaysValueLabel, "112.5");
    lv_label_set_text_static(GUI_Label__OdometerScreen__30DaysUnitLabel, "km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ThisYearTitleLabel, "THIS YEAR");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ThisYearValueLabel, "1021.4");
    lv_label_set_text_static(GUI_Label__OdometerScreen__ThisYearUnitLabel, "km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LongestRunTitleLabel, "LONGEST RUN");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LongestRunValueLabel, "42.66");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LongestRunUnitLabel, "km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunDistanceLabel, "42.66 km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunTimeLabel, "3h 40m");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunPaceLabel, "5:11 /km");
    lv_label_set_text_static(GUI_Label__OdometerScreen__LastRunElevationLabel, "390 m");
    lv_label_set_text_static(GUI_Label__OdometerScreen__DaysUntilValueLabel, "112");
    lv_label_set_text_static(GUI_Label__OdometerScreen__DaysUntilTextLabel, "DAYS UNTIL");
    lv_label_set_text_static(GUI_Label__OdometerScreen__NextRaceLabel, "ST. JUDE MEMPHIS MARATHON");
    lv_label_set_text_static(GUI_Label__OdometerScreen__UpdatedTextLabel, "UPDATED");
    lv_label_set_text_static(GUI_Label__OdometerScreen__UpdatedTimeLabel, "8:42 AM");
}

void GUI_initScreenStyles__OdometerScreen() {
    static lv_style_t GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT);
    lv_style_set_opa(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, 255);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, &jbm48);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_style_set_flex_flow(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, LV_FLEX_FLOW_ROW);
    lv_style_set_layout(&GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT, LV_LAYOUT_NONE);
    lv_obj_add_style(GUI_Label__OdometerScreen__MainTitle, &GUI_Style__Label__OdometerScreen__MainTitle__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Container__OdometerScreen__Divider,
                     &GUI_Style__Container__OdometerScreen__Divider__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT);
    lv_style_set_bg_color(&GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_bg_opa(&GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT, 255);
    lv_style_set_radius(&GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Container__OdometerScreen__VerticalDivider,
                     &GUI_Style__Container__OdometerScreen__VerticalDivider__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunDateLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunDateLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__DistanceTitleLabel,
                     &GUI_Style__Label__OdometerScreen__DistanceTitleLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__DistanceValueLabel,
                     &GUI_Style__Label__OdometerScreen__DistanceValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__DistanceUnitLabel,
                     &GUI_Style__Label__OdometerScreen__DistanceUnitLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__RunsTitleLabel,
                     &GUI_Style__Label__OdometerScreen__RunsTitleLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__RunsValueLabel,
                     &GUI_Style__Label__OdometerScreen__RunsValueLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__TimeTitleLabel,
                     &GUI_Style__Label__OdometerScreen__TimeTitleLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__TimeValueLabel,
                     &GUI_Style__Label__OdometerScreen__TimeValueLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__TimeUnitLabel,
                     &GUI_Style__Label__OdometerScreen__TimeUnitLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ElevationTitleLabel,
                     &GUI_Style__Label__OdometerScreen__ElevationTitleLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ElevationValueLabel,
                     &GUI_Style__Label__OdometerScreen__ElevationValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ElevationUnitLabel,
                     &GUI_Style__Label__OdometerScreen__ElevationUnitLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__7DaysTitleLabel,
                     &GUI_Style__Label__OdometerScreen__7DaysTitleLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__7DaysValueLabel,
                     &GUI_Style__Label__OdometerScreen__7DaysValueLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__7DaysUnitLabel,
                     &GUI_Style__Label__OdometerScreen__7DaysUnitLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__30DaysTitleLabel,
                     &GUI_Style__Label__OdometerScreen__30DaysTitleLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__30DaysValueLabel,
                     &GUI_Style__Label__OdometerScreen__30DaysValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__30DaysUnitLabel,
                     &GUI_Style__Label__OdometerScreen__30DaysUnitLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ThisYearTitleLabel,
                     &GUI_Style__Label__OdometerScreen__ThisYearTitleLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ThisYearValueLabel,
                     &GUI_Style__Label__OdometerScreen__ThisYearValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__ThisYearUnitLabel,
                     &GUI_Style__Label__OdometerScreen__ThisYearUnitLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LongestRunTitleLabel,
                     &GUI_Style__Label__OdometerScreen__LongestRunTitleLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT, &jbm32);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LongestRunValueLabel,
                     &GUI_Style__Label__OdometerScreen__LongestRunValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LongestRunUnitLabel,
                     &GUI_Style__Label__OdometerScreen__LongestRunUnitLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__OdometerScreen__DistanceIcon, &upload_route_png);

    static lv_style_t GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT);
    lv_style_set_min_width(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_scale_y(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_rotation(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__OdometerScreen__DistanceIcon,
                     &GUI_Style__Image__OdometerScreen__DistanceIcon__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunDistanceLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunDistanceLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__OdometerScreen__TimeIcon, &upload_timer_png);

    static lv_style_t GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT);
    lv_style_set_min_width(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_scale_y(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_rotation(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__OdometerScreen__TimeIcon, &GUI_Style__Image__OdometerScreen__TimeIcon__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_RIGHT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunTimeLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunTimeLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__OdometerScreen__PaceIcon, &upload_sportshoe_1_png);

    static lv_style_t GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT);
    lv_style_set_min_width(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_scale_y(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 256);
    lv_style_set_transform_rotation(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__OdometerScreen__PaceIcon, &GUI_Style__Image__OdometerScreen__PaceIcon__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunPaceLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunPaceLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT,
                            LV_TEXT_ALIGN_RIGHT);
    lv_obj_add_style(GUI_Label__OdometerScreen__LastRunElevationLabel,
                     &GUI_Style__Label__OdometerScreen__LastRunElevationLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(GUI_Image__OdometerScreen__TimeIcon_1, &upload_triangleright_png);

    static lv_style_t GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT);
    lv_style_set_min_width(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 0);
    lv_style_set_max_width(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 8000);
    lv_style_set_min_height(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 0);
    lv_style_set_max_height(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 8000);
    lv_style_set_transform_scale_x(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 256);
    lv_style_set_transform_scale_y(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 256);
    lv_style_set_transform_rotation(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_x(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 0);
    lv_style_set_transform_pivot_y(&GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT, 0);
    lv_obj_add_style(GUI_Image__OdometerScreen__TimeIcon_1, &GUI_Style__Image__OdometerScreen__TimeIcon_1__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT, &jbm24);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__DaysUntilValueLabel,
                     &GUI_Style__Label__OdometerScreen__DaysUntilValueLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT,
                            lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__DaysUntilTextLabel,
                     &GUI_Style__Label__OdometerScreen__DaysUntilTextLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, &jbm16);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__NextRaceLabel,
                     &GUI_Style__Label__OdometerScreen__NextRaceLabel__MAIN_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__UpdatedTextLabel,
                     &GUI_Style__Label__OdometerScreen__UpdatedTextLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT;
    lv_style_init(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT);
    lv_style_set_text_font(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, &jbm12);
    lv_style_set_text_color(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, lv_color_make(0, 0, 0));
    lv_style_set_text_opa(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, 255);
    lv_style_set_text_letter_space(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_line_space(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, 0);
    lv_style_set_text_align(&GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT, LV_TEXT_ALIGN_LEFT);
    lv_obj_add_style(GUI_Label__OdometerScreen__UpdatedTimeLabel,
                     &GUI_Style__Label__OdometerScreen__UpdatedTimeLabel__MAIN_DEFAULT,
                     LV_PART_MAIN | LV_STATE_DEFAULT);
}
