// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#ifndef _GUI_H
#define _GUI_H

#include "core/gui_core.h"

#include "core/variables.h"

#include "helpers/ui_helpers.h"

#include "components/comp.h"

#include "components/comp_hook.h"

LV_FONT_DECLARE(jbm12);
LV_FONT_DECLARE(jbm32);
LV_FONT_DECLARE(jbm24);
LV_FONT_DECLARE(jbm48);
LV_IMG_DECLARE(upload_route_png);
LV_FONT_DECLARE(jbm16);
LV_IMG_DECLARE(upload_timer_png);
LV_IMG_DECLARE(upload_sportshoe_1_png);
LV_IMG_DECLARE(upload_triangleright_png);
LV_IMG_DECLARE(upload_wifi_png);
LV_IMG_DECLARE(upload_wifioff_png);

#endif
