// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#ifndef _RUNNINGODOMETER_UI_COMP_HOOK_H
#define _RUNNINGODOMETER_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_StatRow_component_create_hook(lv_obj_t *comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
