// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#ifndef _UI_COMP_STATROW_COMPONENT_H
#define _UI_COMP_STATROW_COMPONENT_H

#include "../GUI.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT StatRow_component
#define UI_COMP_STATROW_COMPONENT 0
#define UI_COMP_STATROW_COMPONENT_STATROWLABEL 1
#define UI_COMP_STATROW_COMPONENT_STAT 2
#define UI_COMP_STATROW_COMPONENT_UNIT 3
#define _UI_COMP_STATROW_COMPONENT_NUM 4
lv_obj_t *ui_StatRow_component_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
