// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#include "../GUI.h"

// COMPONENT StatRow_component

lv_obj_t *ui_StatRow_component_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_StatRow_component_root_bUtmryVUddeNvD;
    cui_StatRow_component_root_bUtmryVUddeNvD = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_StatRow_component_root_bUtmryVUddeNvD);
    lv_obj_set_width(cui_StatRow_component_root_bUtmryVUddeNvD, 180);
    lv_obj_set_height(cui_StatRow_component_root_bUtmryVUddeNvD, 72);
    lv_obj_set_align(cui_StatRow_component_root_bUtmryVUddeNvD, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_StatRow_component_root_bUtmryVUddeNvD, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(cui_StatRow_component_root_bUtmryVUddeNvD, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *cui_StatRowLabel_label_p0W5cQdKL9jpDW;
    cui_StatRowLabel_label_p0W5cQdKL9jpDW = lv_label_create(cui_StatRow_component_root_bUtmryVUddeNvD);
    lv_obj_set_width(cui_StatRowLabel_label_p0W5cQdKL9jpDW, LV_SIZE_CONTENT);
    lv_obj_set_height(cui_StatRowLabel_label_p0W5cQdKL9jpDW, LV_SIZE_CONTENT);
    lv_obj_set_y(cui_StatRowLabel_label_p0W5cQdKL9jpDW, 5);
    lv_obj_set_align(cui_StatRowLabel_label_p0W5cQdKL9jpDW, LV_ALIGN_TOP_LEFT);
    lv_label_set_text_static(cui_StatRowLabel_label_p0W5cQdKL9jpDW, "ALL TIME DISTANCE");
    lv_label_set_long_mode(cui_StatRowLabel_label_p0W5cQdKL9jpDW, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_color(cui_StatRowLabel_label_p0W5cQdKL9jpDW, lv_color_make(0, 0, 0),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_StatRowLabel_label_p0W5cQdKL9jpDW, &jbm12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_StatRowLabel_label_p0W5cQdKL9jpDW, LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_Stat_label_wnAjNaQGUj2oy1;
    cui_Stat_label_wnAjNaQGUj2oy1 = lv_label_create(cui_StatRow_component_root_bUtmryVUddeNvD);
    lv_obj_set_width(cui_Stat_label_wnAjNaQGUj2oy1, LV_SIZE_CONTENT);
    lv_obj_set_height(cui_Stat_label_wnAjNaQGUj2oy1, LV_SIZE_CONTENT);
    lv_obj_set_y(cui_Stat_label_wnAjNaQGUj2oy1, 5);
    lv_obj_set_align(cui_Stat_label_wnAjNaQGUj2oy1, LV_ALIGN_LEFT_MID);
    lv_label_set_text_static(cui_Stat_label_wnAjNaQGUj2oy1, "1000.0");
    lv_label_set_long_mode(cui_Stat_label_wnAjNaQGUj2oy1, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_color(cui_Stat_label_wnAjNaQGUj2oy1, lv_color_make(0, 0, 0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Stat_label_wnAjNaQGUj2oy1, &jbm32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Stat_label_wnAjNaQGUj2oy1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_Unit_label_J8OSEBiIqc6MkH;
    cui_Unit_label_J8OSEBiIqc6MkH = lv_label_create(cui_StatRow_component_root_bUtmryVUddeNvD);
    lv_obj_set_width(cui_Unit_label_J8OSEBiIqc6MkH, LV_SIZE_CONTENT);
    lv_obj_set_height(cui_Unit_label_J8OSEBiIqc6MkH, LV_SIZE_CONTENT);
    lv_obj_set_x(cui_Unit_label_J8OSEBiIqc6MkH, -10);
    lv_obj_set_y(cui_Unit_label_J8OSEBiIqc6MkH, 6);
    lv_obj_set_align(cui_Unit_label_J8OSEBiIqc6MkH, LV_ALIGN_RIGHT_MID);
    lv_label_set_text_static(cui_Unit_label_J8OSEBiIqc6MkH, "km");
    lv_label_set_long_mode(cui_Unit_label_J8OSEBiIqc6MkH, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_color(cui_Unit_label_J8OSEBiIqc6MkH, lv_color_make(0, 0, 0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Unit_label_J8OSEBiIqc6MkH, &jbm24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Unit_label_J8OSEBiIqc6MkH, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_STATROW_COMPONENT_NUM);
    children[UI_COMP_STATROW_COMPONENT] = cui_StatRow_component_root_bUtmryVUddeNvD;
    children[UI_COMP_STATROW_COMPONENT_STATROWLABEL] = cui_StatRowLabel_label_p0W5cQdKL9jpDW;
    children[UI_COMP_STATROW_COMPONENT_STAT] = cui_Stat_label_wnAjNaQGUj2oy1;
    children[UI_COMP_STATROW_COMPONENT_UNIT] = cui_Unit_label_J8OSEBiIqc6MkH;
    lv_obj_add_event_cb(cui_StatRow_component_root_bUtmryVUddeNvD, get_component_child_event_cb,
                        LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_StatRow_component_root_bUtmryVUddeNvD, del_component_child_event_cb, LV_EVENT_DELETE,
                        children);
    ui_comp_StatRow_component_create_hook(cui_StatRow_component_root_bUtmryVUddeNvD);
    return cui_StatRow_component_root_bUtmryVUddeNvD;
}
