// This file was generated by SquareLine Vision Exporter
// Project name: RunningOdometer

#ifndef _GUI_CORE_H
#define _GUI_CORE_H

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

// Screen-specific function declarations
void GUI_initScreen__OdometerScreen();
void GUI_initScreenTexts__OdometerScreen();
void GUI_initScreenStyles__OdometerScreen();

void GUI_load();

void GUI_init();

void GUI_refresh();

void GUI_initHAL();
void HAL_init();

void GUI_initFramework();

void GUI_loadContent();

void GUI_initContent();

void GUI_initTheme();

void GUI_initScreens();

void GUI_loadFirstScreen();

void GUI_initScreenContents();

void GUI_initScreenTexts();

void GUI_initScreenStyles();

void GUI_initAnimations();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
